name: Build Vim

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'

env:
  VIMREPO: https://github.com/vim/vim
  MQREPO: http://hg.pf.osdn.net/view/k/k_/k_takata/vim-ktakata-mq
  VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
  GITBIN: C:\Program Files\Git\usr\bin

  # Interfaces
  # Lua
  LUA_VER: 53
  LUA_VER_DOT: 5.3
  LUA_RELEASE: 5.3.5
  LUA32_URL: https://downloads.sourceforge.net/luabinaries/lua-%LUA_RELEASE%_Win32_dllw6_lib.zip
  LUA64_URL: https://downloads.sourceforge.net/luabinaries/lua-%LUA_RELEASE%_Win64_dllw6_lib.zip
  LUA_DIR: D:\Lua
  # Perl
  PERL_VER: 530
  PERL_VER_DOT: 5.30
  PERL_RELEASE: 5.30.1.1
  PERL32_URL: http://strawberryperl.com/download/%PERL_RELEASE%/strawberry-perl-%PERL_RELEASE%-32bit-portable.zip
  PERL64_URL: http://strawberryperl.com/download/%PERL_RELEASE%/strawberry-perl-%PERL_RELEASE%-64bit-portable.zip
  PERL_DIR: D:\Strawberry\perl
  # Python 3
  PYTHON3_VER: 38
  PYTHON3_VER_DOT: 3.8
  PYTHON3_DIR_BASE: C:\hostedtoolcache\windows\Python\3.8.0
  # Ruby
  RUBY_VER: 26
  RUBY_VER_DOT: 2.6
  RUBY_API_VER_LONG: 2.6.0
  RUBY_BRANCH: ruby_2_6
  RUBY_RELEASE: 2.6.5-1
  RUBY_SRC_URL: https://github.com/ruby/ruby/archive/%RUBY_BRANCH%.zip
  RUBY32_URL: https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-%RUBY_RELEASE%/rubyinstaller-%RUBY_RELEASE%-x86.7z
  RUBY64_URL: https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-%RUBY_RELEASE%/rubyinstaller-%RUBY_RELEASE%-x64.7z
  RUBY_DIR: D:\rubyinstaller

  # Other dependencies
  # gettext
  GETTEXT32_URL: https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.19.8.1-v1.15/gettext0.19.8.1-iconv1.15-shared-32.zip
  GETTEXT64_URL: https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.19.8.1-v1.15/gettext0.19.8.1-iconv1.15-shared-64.zip
  GETTEXT_DIR: D:\gettext
  # winpty
  WINPTY_URL: https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-msvc2015.zip

  # Escape sequences
  COL_RED: "\x1b[31m"
  COL_GREEN: "\x1b[32m"
  COL_YELLOW: "\x1b[33m"
  COL_RESET: "\x1b[m"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, x86]
        include:
          - arch: x64
            vcarch: amd64
            warch: x64
            bits: 64
          - arch: x86
            vcarch: x86
            warch: ia32
            bits: 32

    steps:
    - name: Initalize
      id: init
      shell: bash
      run: |
        echo "::set-output name=date::$(date +%Y%m%d)"
        git config --global core.autocrlf input
        echo "::set-env name=PYTHON3_DIR::$PYTHON3_DIR_BASE\\${{ matrix.arch }}"

    - uses: actions/checkout@v2
    - name: Checkout and update submodules
      shell: bash
      run: |
        # Checkout the lastest version, ignore error
        git submodule update --init --depth 1 || true
        for i in contrib/*/; do
          git -C $i checkout master
        done

#    # See: https://github.com/nelsonjchen/reverse-rdp-windows-github-actions
#    - name: Enable RDP
#      env:
#        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
#      run: |
#        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
#        Expand-Archive ngrok.zip
#        .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
#        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
#        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
#        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
#        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
#        Start-Process .\ngrok\ngrok.exe -ArgumentList "tcp 3389"

    - name: Checkout Vim
      shell: bash
      run: |
        if ! git clone ${VIMREPO}.git --shallow-exclude="$(cat vimver.txt)"; then
          if [ "${{ github.event_name }}" = 'pull_request' ]; then
            git clone ${VIMREPO}.git --depth=5
          else
            exit 0
          fi
        fi
        cd vim
        patches=.hg/patches
        hg clone $MQREPO $patches
        # Apply patches
        sed -e '/ #+/d' -e 's/ #-.*$//' $patches/series | \
          xargs -I{} patch -p1 -i $patches/{}
        git log -4 --color=always

    - name: Get changelog
      id: changelog
      shell: bash
      run: |
        mkdir package/artifacts
        if [ ! -d vim ]; then
          cp vimver.txt package/artifacts/latest.txt
          touch package/artifacts/changelog.txt
          exit 0
        fi
        cd vim
        latest=$(git describe --tags --abbrev=0)
        echo "::set-output name=ref::${latest:1}"
        echo $latest > ../package/artifacts/latest.txt
        vimver=$(cat ../vimver.txt)
        cp ../package/artifacts/latest.txt ../vimver.txt
        commiturl=${VIMREPO}/commit/
        git log --format='format:%H %s' | \
          sed -e 's/[][_*^<`\\]/\\&/g' \
              -e 's/%/%25/g' \
              -e "s#^\([0-9a-f]*\) patch \([0-9.a-z]*\): #* [\2]($commiturl\1): #" \
              -e "s#^\([0-9a-f]*\) \(.*\)#* [\2]($commiturl\1)#" | \
          sed -e ':a;N;$!ba;s/\n/%0A/g' | \
          tee ../package/artifacts/changelog.txt

    - name: Check changes
      id: check
      shell: bash
      run: |
        if git diff --quiet HEAD vimver.txt; then
          echo ${COL_YELLOW}No updates.${COL_RESET}
          echo "::set-output name=skip::yes"
        else
          echo "::set-output name=skip::no"
        fi

#    - name: Create a list of download URLs
#      if: steps.check.outputs.skip == 'no' || github.event_name == 'pull_request'
#      shell: cmd
#      run: |
#        type NUL > urls.txt
#        echo %LUA${{ matrix.bits }}_URL%>> urls.txt
#        echo %PERL${{ matrix.bits }}_URL%>> urls.txt
#        echo %RUBY${{ matrix.bits }}_URL%>> urls.txt
#        echo %GETTEXT${{ matrix.bits }}_URL%>> urls.txt
#        echo %WINPTY_URL%>> urls.txt
#
#    - name: Cache downloaded files
#      if: steps.check.outputs.skip == 'no' || github.event_name == 'pull_request'
#      uses: actions/cache@v1
#      with:
#        path: downloads
#        key: ${{ runner.os }}-${{ matrix.bits }}-${{ hashFiles('urls.txt') }}

    - name: Download dependencies
      if: steps.check.outputs.skip == 'no' || github.event_name == 'pull_request'
      shell: cmd
      run: |
        path C:\Program Files\7-Zip;%path%

        echo %COL_GREEN%Download Lua%COL_RESET%
        call :downloadfile %LUA${{ matrix.bits }}_URL% downloads\lua.zip
        7z x downloads\lua.zip -o%LUA_DIR% > nul || exit 1

        echo %COL_GREEN%Download Perl%COL_RESET%
        call :downloadfile %PERL${{ matrix.bits }}_URL% downloads\perl.zip
        :: Extract only the "perl" folder.
        7z x downloads\perl.zip perl -o%PERL_DIR%\.. > nul || exit 1

        echo %COL_GREEN%Download Ruby%COL_RESET%
        call :downloadfile %RUBY${{ matrix.bits }}_URL% downloads\ruby.zip
        7z x downloads\ruby.zip -oD:\ > nul || exit 1
        move D:\rubyinstaller-%RUBY_RELEASE%-${{ matrix.arch }} %RUBY_DIR% > nul || exit 1

        echo %COL_GREEN%Download Ruby source%COL_RESET%
        call :downloadfile %RUBY_SRC_URL% downloads\ruby_src.zip
        :: Extract the files only we needed to reduce the building time.
        7z x downloads\ruby_src.zip */bin */enc/Makefile.in */win32 */common.mk -ir!version.h -xr!README.* -xr!*/win32/*.c -xr!*/win32/*.h -o.. > nul || exit 1
        move ..\ruby-%RUBY_BRANCH% ..\ruby > nul || exit 1

        echo %COL_GREEN%Download gettext%COL_RESET%
        call :downloadfile %GETTEXT${{ matrix.bits }}_URL% downloads\gettext.zip
        7z e -y downloads\gettext.zip -o%GETTEXT_DIR% > nul || exit 1

        echo %COL_GREEN%Download winpty%COL_RESET%
        call :downloadfile %WINPTY_URL% downloads\winpty.zip
        7z x -y downloads\winpty.zip -oD:\winpty > nul || exit 1
        copy /Y D:\winpty\${{ matrix.warch }}\bin\winpty.dll        vim\src\winpty${{ matrix.bits }}.dll
        copy /Y D:\winpty\${{ matrix.warch }}\bin\winpty-agent.exe  vim\src\

        goto :eof

        :downloadfile
        :: call :downloadfile <URL> <localfile>
        if not exist %2 (
          curl -f -L %1 -o %2 || exit 1
        )
        goto :eof

    - name: Create Ruby's config.h
      if: steps.check.outputs.skip == 'no' || github.event_name == 'pull_request'
      shell: cmd
      run: |
        call "%VCVARSALL%" ${{ matrix.vcarch }}
        cd ..\ruby
        call win32\configure.bat
        nmake -nologo .config.h.time || exit 1
        xcopy /s .ext\include %RUBY_DIR%\include\ruby-%RUBY_API_VER_LONG%

    - name: Update ja.po
      if: steps.check.outputs.skip == 'no' || github.event_name == 'pull_request'
      shell: cmd
      run: |
        call "%VCVARSALL%" ${{ matrix.vcarch }}
        copy /y contrib\lang-ja\src\po\ja.po vim\src\po
        cd vim\src\po
        cl sjiscorr.c
        iconv -f utf-8 -t cp932 ja.po | sjiscorr | dos2unix > ja.sjis.po
        iconv -f utf-8 -t euc-jp ja.po | sed -e "s/charset=[uU][tT][fF]-8/charset=euc-jp/" -e "s/# Original translations/# Generated from ja.po, DO NOT EDIT/" > ja.euc-jp.po

    - name: Update patchlevel
      if: steps.check.outputs.skip == 'no' || github.event_name == 'pull_request'
      shell: bash
      run: |
        cd vim/src
        patchlevel=$(sed -n -e '/included_patches/{n;n;n;s/ *\([0-9]*\).*/\1/p;q}' version.c)
        sed -i -e "/VIM_VERSION_PATCHLEVEL/s/0/$patchlevel/" version.h

    - name: Build
      if: steps.check.outputs.skip == 'no' || github.event_name == 'pull_request'
      shell: cmd
      run: |
        call "%VCVARSALL%" ${{ matrix.vcarch }}
        cd vim\src
        rem Suppress progress animation
        sed -e "s/@<<$/@<< | sed -e 's#.*\\\\r.*##'/" Make_mvc.mak > Make_mvc2.mak
        rem Build gvim/vim with VIMDLL
        nmake -nologo -f Make_mvc2.mak ^
          GUI=yes IME=yes ICONV=yes VIMDLL=yes ^
          DYNAMIC_LUA=yes LUA=%LUA_DIR% ^
          DYNAMIC_PERL=yes PERL=%PERL_DIR% ^
          DYNAMIC_PYTHON3=yes PYTHON3=%PYTHON3_DIR% ^
          DYNAMIC_RUBY=yes RUBY=%RUBY_DIR% RUBY_MSVCRT_NAME=msvcrt ^
          || exit 1
        if not exist vim${{ matrix.bits }}.dll (
          echo %COL_RED%Build failure.%COL_RESET%
          exit 1
        )
        cd po
        nmake -nologo -f Make_mvc.mak GETTEXT_PATH="\"%GITBIN%\"" || exit 1
        nmake -nologo -f Make_mvc.mak install-all

    - name: Test
      if: steps.check.outputs.skip == 'no' || github.event_name == 'pull_request'
      shell: cmd
      run: |
        path %LUA_DIR%;%PERL_DIR%\bin;%PYTHON3_DIR%;%RUBY_DIR%\bin;%RUBY_DIR%\bin\ruby_builtin_dlls;%GETTEXT_DIR%;%path%
        call "%VCVARSALL%" ${{ matrix.vcarch }}
        cd vim\src
        echo.
        echo %COL_GREEN%gvim version:%COL_RESET%
        start /wait .\gvim -u NONE -c "redir @a | ver | put a | 1,3d | wq!" ver.txt
        type ver.txt || exit 1
        start /wait .\gvim -u NONE -S ..\..\scripts\if_ver.vim -c quit
        type if_ver.txt
        echo %COL_GREEN%vim version:%COL_RESET%
        .\vim --version || exit 1
        .\vim --not-a-term -u NONE -S ..\..\scripts\if_ver.vim -c quit
        type if_ver.txt
        cd testdir
        echo %COL_GREEN%Test gvim:%COL_RESET%
        nmake -nologo -f Make_dos.mak VIMPROG=..\gvim || exit 1
        nmake -nologo -f Make_dos.mak clean
        echo %COL_GREEN%Test vim:%COL_RESET%
        start /wait nmake -nologo -f Make_dos.mak VIMPROG=..\vim
        nmake -nologo -f Make_dos.mak report || exit 1

    - name: Package
      if: steps.check.outputs.skip == 'no' || github.event_name == 'pull_request'
      shell: cmd
      run: |
        cd package
        set DEST=vim-kt-win${{ matrix.bits }}
        md %DEST%
        copy ..\vim\src\*.pdb     .
        copy ..\vim\src\*vim*.exe %DEST%
        copy ..\vim\src\vim*.dll  %DEST%
        copy ..\vim\src\tee\*.exe %DEST%
        copy ..\vim\src\xxd\*.exe %DEST%
        copy ..\vim\src\winpty*   %DEST%
        copy ..\README.md         %DEST%
        copy %LUA_DIR%\lua*.dll   %DEST%
        copy %GETTEXT_DIR%\libiconv-2.dll %DEST%
        copy %GETTEXT_DIR%\libintl-8.dll  %DEST%
        if exist %GETTEXT_DIR%\libgcc_s_sjlj-1.dll copy %GETTEXT_DIR%\libgcc_s_sjlj-1.dll %DEST%
        xcopy ..\vim\runtime %DEST%\runtime /Y /E /V /I /H /R /Q
        md %DEST%\runtime\pack\dist-kt\start
        :: Don't copy hidden files
        xcopy ..\contrib\autofmt   %DEST%\runtime\pack\dist-kt\start\autofmt   /Y /E /V /I /R /Q
        del %DEST%\runtime\pack\dist-kt\start\autofmt\.gitignore
        xcopy ..\contrib\vimdoc-ja %DEST%\runtime\pack\dist-kt\start\vimdoc-ja /Y /E /V /I /R /Q
        del %DEST%\runtime\pack\dist-kt\start\vimdoc-ja\.gitignore
        rem md artifacts
        set BASENAME=vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win${{ matrix.bits }}
        7z a artifacts\%BASENAME%.zip %DEST%
        7z a artifacts\%BASENAME%.7z  %DEST%
        7z a artifacts\%BASENAME%-pdb.7z *.pdb

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: vim-kt-win${{ matrix.bits }}
        path: ./package/artifacts

  release:
    runs-on: windows-latest
    needs: [build]
    if: github.event_name != 'pull_request'

    steps:
    - name: Initalize
      id: init
      shell: bash
      run: |
        echo "::set-output name=date::$(date +%Y%m%d)"
        git config --global core.autocrlf input

    - uses: actions/checkout@v2
    - name: Checkout and update submodules
      shell: bash
      run: |
        # Checkout the lastest version, ignore error
        git submodule update --init --depth 1 || true
        for i in contrib/*/; do
          git -C $i checkout master
        done

    - name: Download Artifact (win32)
      uses: actions/download-artifact@v1
      with:
        name: vim-kt-win32

    - name: Download Artifact (win64)
      uses: actions/download-artifact@v1
      with:
        name: vim-kt-win64

    - name: Get changelog
      id: changelog
      shell: bash
      run: |
        changelog=$(cat vim-kt-win64/changelog.txt)
        echo "::set-output name=log::$changelog"
        latest=$(cat vim-kt-win64/latest.txt)
        echo "::set-output name=ref::${latest:1}"
        echo $latest > vimver.txt

    - name: Commit and push
      id: commit
      shell: bash
      run: |
        if git diff --quiet HEAD vimver.txt; then
          echo ${COL_YELLOW}No updates.${COL_RESET}
          echo "::set-output name=skip::yes"
        else
          git config --local user.name "vim-kt CI"
          git config --local user.email "k-takata@users.noreply.github.com"
          git commit -a -m "Update Vim to v${{ steps.changelog.outputs.ref }}"
          git tag "v${{ steps.changelog.outputs.ref }}"
          git push --tags
          git push
          echo "::set-output name=skip::no"
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      if: steps.commit.outputs.skip == 'no'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.changelog.outputs.ref }}
        release_name:  v${{ steps.changelog.outputs.ref }}
        body: |
          ### Changes:

          ${{ steps.changelog.outputs.log }}

          ### Compiled with:

          * [LuaBinaries](http://luabinaries.sourceforge.net/download.html) ${{ env.LUA_VER_DOT }}
          * [Strawberry Perl](http://strawberryperl.com/) ${{ env.PERL_VER_DOT }}
          * [Python3](https://www.python.org/downloads/) ${{ env.PYTHON3_VER_DOT }}
          * [RubyInstaller2](https://rubyinstaller.org/downloads/) ${{ env.RUBY_VER_DOT }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (win32)
      uses: actions/upload-release-asset@v1.0.1
      if: steps.commit.outputs.skip == 'no'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vim-kt-win32/vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win32.zip
        asset_name: vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win32.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (win32-7z)
      uses: actions/upload-release-asset@v1.0.1
      if: steps.commit.outputs.skip == 'no'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vim-kt-win32/vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win32.7z
        asset_name: vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win32.7z
        asset_content_type: application/x-7z-compressed

    - name: Upload Release Asset (win32-pdb)
      uses: actions/upload-release-asset@v1.0.1
      if: steps.commit.outputs.skip == 'no'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vim-kt-win32/vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win32-pdb.7z
        asset_name: vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win32-pdb.7z
        asset_content_type: application/x-7z-compressed

    - name: Upload Release Asset (win64)
      uses: actions/upload-release-asset@v1.0.1
      if: steps.commit.outputs.skip == 'no'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vim-kt-win64/vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win64.zip
        asset_name: vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win64.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (win64-7z)
      uses: actions/upload-release-asset@v1.0.1
      if: steps.commit.outputs.skip == 'no'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vim-kt-win64/vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win64.7z
        asset_name: vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win64.7z
        asset_content_type: application/x-7z-compressed

    - name: Upload Release Asset (win64-pdb)
      uses: actions/upload-release-asset@v1.0.1
      if: steps.commit.outputs.skip == 'no'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vim-kt-win64/vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win64-pdb.7z
        asset_name: vim-kt-${{ steps.changelog.outputs.ref }}-${{ steps.init.outputs.date }}-win64-pdb.7z
        asset_content_type: application/x-7z-compressed

# vim: ts=2 sw=2 sts=2 et
