name: Build Vim

on: push

env:
  VIMREPO: https://hg.osdn.net/view/vim/vim
  MQREPO: http://hg.pf.osdn.net/view/k/k_/k_takata/vim-ktakata-mq
  HG: hg --config extensions.mq= --config "ui.username=%USERNAME% <%USERNAME%@%USERDOMAIN%>"
  VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat


jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, x86]
        include:
          - arch: x64
            vcarch: amd64
            bits: 64
          - arch: x86
            vcarch: x86
            bits: 32

    steps:
    - uses: actions/checkout@v2

    - name: Checkout Vim
      shell: cmd
      run: |
        call %HG% qclone %VIMREPO% -p %MQREPO% vim
        cd vim
        hg log -v -r -1:-4
        call %HG% qpush -a
        cd ..

    - name: Build
      shell: cmd
      run: |
        call "%VCVARSALL%" ${{ matrix.vcarch }}
        cd vim\src
        rem Suppress progress animation
        sed -e "s/@<<$/@<< | sed -e 's#.*\\\\r.*##'/" Make_mvc.mak > Make_mvc2.mak
        rem Build gvim/vim with VIMDLL
        nmake -f Make_mvc2.mak GUI=yes IME=yes ICONV=yes VIMDLL=yes || exit 1
        rem Show gvim version
        start /wait .\gvim -u NONE -c "redir @a | ver | 0put a | wq!" ver.txt
        type ver.txt || exit 1
        rem Show vim version
        .\vim --version || exit 1

# vim: ts=2 sw=2 sts=2 et
